version: "3.8"

services:
  web:
    container_name: blog-api-web
    image: sdelowar2/blog-api-drf:latest
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env  
    # volumes:
    #   - .:/app

  
  db:
    container_name: blog-api-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  

    